site_name: PIPE Team Maersk
site_url: https://docs.logitech.dev
repo_url: https://github.com/Maersk/PIPE
repo_name: Maersk/PIPE

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LogiTech
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/logitech
    - icon: fontawesome/brands/slack
      link: https://logitech.slack.com

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CI/CD Pipeline: cicd-pipeline.md
  - Infrastructure: infrastructure.md
  - Monitoring: monitoring.md
  - Best Practices: best-practices.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji