site_name: PIPE Team Maersk
site_url: https://Srinidhi-Yoganand.github.io/portal/
site_description: Maersk DevOps Team Documentation

extra:
  base_url: /portal/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CI/CD Pipeline: cicd-pipeline.md
  - Infrastructure: infrastructure.md
  - Monitoring: monitoring.md
  - Best Practices: best-practices.md

repo_url: https://github.com/Srinidhi-Yoganand/portal/
repo_name: Srinidhi-Yoganand/portal

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji