name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Cancel previous runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for proper versioning

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # Enable caching for faster builds

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install from requirements.txt if exists, otherwise specific packages
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install mkdocs mkdocs-material
        fi

    - name: Build site with verbose output
      run: |
        mkdocs build --strict --verbose --site-dir site
        echo "Build completed. Site structure:"
        find site/ -type f -name "*.html" | head -10

    - name: Verify build output
      run: |
        # Check if essential files were built
        if [ ! -f "site/index.html" ]; then
          echo "ERROR: index.html not found in build output!"
          exit 1
        fi
        if [ ! -f "site/styles/extra.css" ]; then
          echo "WARNING: extra.css not found in build output!"
        fi
        echo "Build verification passed!"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages  # Explicitly set branch
        force_orphan: true  # Clean history for smaller repo size
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Post-deployment verification
      if: success()
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "Your site will be available at:"
        echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        echo ""
        echo "Note: It may take 1-2 minutes for GitHub Pages to update."